const AUDIT_ACTIONS = {
  CRANE_CREATED: "CRANE_CREATED",
  CRANE_UPDATED: "CRANE_UPDATED",
  CRANE_DELETED: "CRANE_DELETED",

  FORBIDDEN_CRANE_UPDATE: "FORBIDDEN_CRANE_UPDATE",
  FORBIDDEN_CRANE_DELETE: "FORBIDDEN_CRANE_DELETE",

  ADMIN_CRANE_LIST_VIEWED: "ADMIN_CRANE_LIST_VIEWED",
};

module.exports = AUDIT_ACTIONS;
